import { useCallback, useRef } from "react";

/**
 * Tiny audio cue library via Web Audio API. No bundled assets — every
 * sound is generated by an OscillatorNode + GainNode envelope.
 *
 * Cues:
 *   tick   — short high blip when the menu cursor moves
 *   select — sine sweep when an item is activated
 *   bloop  — sub-bass blip when a tool call starts
 *   chime  — two-note arpeggio when an itinerary is ready
 *   error  — low square wave on error
 *
 * All cues short-circuit when `muted` is true. Lazy-creates the
 * AudioContext on the first call so we don't trip browser autoplay
 * restrictions before the user has interacted.
 */
export function useAudioCues({ muted = false } = {}) {
  const ctxRef = useRef(null);

  const getCtx = useCallback(() => {
    if (typeof window === "undefined") return null;
    if (!ctxRef.current) {
      const AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) return null;
      ctxRef.current = new AC();
    }
    return ctxRef.current;
  }, []);

  const play = useCallback(
    ({ freq, durationMs, type = "sine", gain = 0.04, sweepTo = null }) => {
      if (muted) return;
      const ctx = getCtx();
      if (!ctx) return;
      try {
        const osc = ctx.createOscillator();
        const g = ctx.createGain();
        osc.type = type;
        osc.frequency.value = freq;
        if (sweepTo != null) {
          osc.frequency.exponentialRampToValueAtTime(
            sweepTo,
            ctx.currentTime + durationMs / 1000,
          );
        }
        g.gain.value = 0;
        // ADSR-ish envelope: 5ms attack, hold, 30ms release
        const now = ctx.currentTime;
        const peak = gain;
        const releaseStart = now + (durationMs - 30) / 1000;
        const stop = now + durationMs / 1000;
        g.gain.setValueAtTime(0, now);
        g.gain.linearRampToValueAtTime(peak, now + 0.005);
        g.gain.setValueAtTime(peak, releaseStart);
        g.gain.linearRampToValueAtTime(0, stop);
        osc.connect(g);
        g.connect(ctx.destination);
        osc.start(now);
        osc.stop(stop);
      } catch {
        // Ignore audio errors — cues are non-essential
      }
    },
    [muted, getCtx],
  );

  const tick = useCallback(
    () => play({ freq: 800, durationMs: 60, type: "square", gain: 0.025 }),
    [play],
  );
  const select = useCallback(
    () => play({ freq: 600, sweepTo: 1200, durationMs: 120, type: "sine", gain: 0.05 }),
    [play],
  );
  const bloop = useCallback(
    () => play({ freq: 220, durationMs: 200, type: "sine", gain: 0.06 }),
    [play],
  );
  const chime = useCallback(() => {
    if (muted) return;
    // Two-note arpeggio C5 → E5
    play({ freq: 523.25, durationMs: 180, type: "sine", gain: 0.06 });
    setTimeout(
      () => play({ freq: 659.25, durationMs: 240, type: "sine", gain: 0.06 }),
      150,
    );
  }, [play, muted]);
  const error = useCallback(
    () => play({ freq: 200, durationMs: 250, type: "square", gain: 0.06 }),
    [play],
  );

  return { tick, select, bloop, chime, error };
}
