"""
Export router — POST /export/pdf

Accepts the full itinerary state (plus optional visa data and checklist
items) and returns a downloadable PDF generated by weasyprint from a
Jinja2 HTML template.
"""

import base64
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

import httpx
from fastapi import HTTPException
from fastapi.responses import Response
from fastapi.routing import APIRouter
from jinja2 import Environment, FileSystemLoader
from pydantic import BaseModel

from app.config import GOOGLE_MAPS_API_KEY
from app.tools.directions import get_directions

log = logging.getLogger(__name__)

router = APIRouter(tags=["export"])

_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"
_jinja_env = Environment(
    loader=FileSystemLoader(str(_TEMPLATES_DIR)),
    autoescape=True,
)

# Google Places photo base URL (same as photo.py)
_PLACES_PHOTO_BASE = "https://places.googleapis.com/v1"


async def _photo_to_data_url(photo_url: str | None, max_width: int = 600) -> str | None:
    """Convert a /photo/... relative backend URL to a base64 data URL for PDF embedding.

    The photo_url from the itinerary is a relative path like:
      /photo/places/ChIJ.../photos/AeXyz...
    We strip the leading /photo/ to get the Places API resource name, then
    fetch the image directly from Google Places and return a data: URL so
    weasyprint can embed it without making network requests.
    """
    if not photo_url:
        return None
    if not GOOGLE_MAPS_API_KEY:
        return None

    # Strip /photo/ prefix to get the resource name
    resource = photo_url.lstrip("/")
    if resource.startswith("photo/"):
        resource = resource[len("photo/"):]

    upstream_url = f"{_PLACES_PHOTO_BASE}/{resource}/media"
    params = {"key": GOOGLE_MAPS_API_KEY, "maxWidthPx": max_width}

    try:
        async with httpx.AsyncClient(timeout=10.0, follow_redirects=True, trust_env=False) as client:
            resp = await client.get(upstream_url, params=params)
            if resp.status_code != 200:
                return None
            content_type = resp.headers.get("content-type", "image/jpeg").split(";")[0]
            b64 = base64.b64encode(resp.content).decode("ascii")
            return f"data:{content_type};base64,{b64}"
    except Exception as exc:
        log.warning("Failed to fetch hotel photo for PDF: %s", exc)
        return None


class ChecklistItem(BaseModel):
    key: str
    label: str
    critical: bool = False
    checked: bool = False


class ExportRequest(BaseModel):
    itinerary: dict[str, Any]
    visa_data: dict[str, Any] | None = None
    checklist_items: list[ChecklistItem] = []


@router.post("/pdf")
async def export_pdf(req: ExportRequest) -> Response:
    """Generate and return a PDF of the trip itinerary."""
    try:
        import weasyprint  # import here so startup doesn't fail if absent
    except ImportError:
        raise HTTPException(
            status_code=500,
            detail="weasyprint is not installed. Run: pip install weasyprint",
        )

    itinerary = req.itinerary
    flight = itinerary.get("flight")
    hotel = itinerary.get("selected_hotel") or (
        itinerary.get("hotels", [None])[0] if itinerary.get("hotels") else None
    )
    days = itinerary.get("days", [])
    phrasebook = itinerary.get("phrasebook")
    selected_flight = itinerary.get("selected_flight")
    selected_return_flight = itinerary.get("selected_return_flight")

    # Fetch hotel photo as a base64 data URL so weasyprint can embed it.
    # selected_hotel from Turn 3 often lacks photo_url (the LLM strips it
    # to reduce output size). Fall back to the matching entry in hotels[].
    hotel_photo_data_url = None
    if hotel:
        photo_url = hotel.get("photo_url")
        if not photo_url:
            # Look up by place_id first, then name
            place_id = hotel.get("place_id")
            name = hotel.get("name", "").lower()
            for h in itinerary.get("hotels", []):
                if (place_id and h.get("place_id") == place_id) or (
                    name and h.get("name", "").lower() == name
                ):
                    photo_url = h.get("photo_url")
                    break
        hotel_photo_data_url = await _photo_to_data_url(photo_url)

    # Fetch activity photos (one per activity, capped to avoid huge PDFs).
    # We build a parallel structure: days_with_photos mirrors `days` but each
    # activity dict gets an injected `_photo_data_url` key for the template.
    import asyncio

    async def _enrich_activity(act: dict) -> dict:
        data_url = await _photo_to_data_url(act.get("photo_url"), max_width=400)
        return {**act, "_photo_data_url": data_url}

    async def _enrich_day(day: dict) -> dict:
        enriched_acts = await asyncio.gather(
            *[_enrich_activity(a) for a in day.get("activities", [])]
        )
        return {**day, "activities": list(enriched_acts)}

    days_with_photos = await asyncio.gather(*[_enrich_day(d) for d in days])

    # Fetch live route steps between consecutive activities for each day.
    # Each destination activity gets a `_route` key with {duration, distance, steps}.
    hotel_obj = itinerary.get("selected_hotel") or {}

    async def _enrich_day_with_routes(day: dict) -> dict:
        acts = list(day.get("activities", []))
        if len(acts) < 2:
            return day
        enriched = list(acts)
        for i in range(1, len(acts)):
            dest = acts[i]
            origin = acts[i - 1] if acts[i - 1].get("lat") and acts[i - 1].get("lng") else hotel_obj
            if not (dest.get("lat") and dest.get("lng") and origin.get("lat") and origin.get("lng")):
                continue
            mode = (acts[i - 1].get("transport_to_next") or {}).get("mode", "TRANSIT")
            try:
                route = await get_directions(
                    f"{origin['lat']},{origin['lng']}",
                    f"{dest['lat']},{dest['lng']}",
                    mode,
                )
            except Exception:
                route = None
            if route and route.get("duration"):
                enriched[i] = {**enriched[i], "_route": route}
        return {**day, "activities": enriched}

    days_final = await asyncio.gather(*[_enrich_day_with_routes(d) for d in days_with_photos])

    # Read the CSS file to inline it into the template
    css_path = _TEMPLATES_DIR / "itinerary.css"
    css_content = css_path.read_text(encoding="utf-8") if css_path.exists() else ""

    try:
        template = _jinja_env.get_template("itinerary.html")
        html_str = template.render(
            itinerary=itinerary,
            flight=flight,
            hotel=hotel,
            hotel_photo=hotel_photo_data_url,
            days=days_final,
            phrasebook=phrasebook,
            selected_flight=selected_flight,
            selected_return_flight=selected_return_flight,
            visa_data=req.visa_data,
            checklist_items=req.checklist_items,
            css=css_content,
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        )
    except Exception as exc:
        log.exception("Template rendering failed: %s", exc)
        raise HTTPException(status_code=500, detail=f"Template error: {exc}")

    try:
        pdf_bytes = weasyprint.HTML(string=html_str).write_pdf()
    except Exception as exc:
        log.exception("weasyprint PDF generation failed: %s", exc)
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {exc}")

    dest = itinerary.get("destination", "trip").replace(" ", "-").lower()
    filename = f"itinerary-{dest}.pdf"

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
