"""
Export router — POST /export/pdf

Accepts the full itinerary state (plus optional visa data and checklist
items) and returns a downloadable PDF generated by weasyprint from a
Jinja2 HTML template.
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from fastapi import HTTPException
from fastapi.responses import Response
from fastapi.routing import APIRouter
from jinja2 import Environment, FileSystemLoader
from pydantic import BaseModel

log = logging.getLogger(__name__)

router = APIRouter(tags=["export"])

_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"
_jinja_env = Environment(
    loader=FileSystemLoader(str(_TEMPLATES_DIR)),
    autoescape=True,
)


class ChecklistItem(BaseModel):
    key: str
    label: str
    critical: bool = False
    checked: bool = False


class ExportRequest(BaseModel):
    itinerary: dict[str, Any]
    visa_data: dict[str, Any] | None = None
    checklist_items: list[ChecklistItem] = []


@router.post("/pdf")
async def export_pdf(req: ExportRequest) -> Response:
    """Generate and return a PDF of the trip itinerary."""
    try:
        import weasyprint  # import here so startup doesn't fail if absent
    except ImportError:
        raise HTTPException(
            status_code=500,
            detail="weasyprint is not installed. Run: pip install weasyprint",
        )

    itinerary = req.itinerary
    flight = itinerary.get("flight")
    hotel = itinerary.get("selected_hotel") or (
        itinerary.get("hotels", [None])[0] if itinerary.get("hotels") else None
    )
    days = itinerary.get("days", [])
    phrasebook = itinerary.get("phrasebook")
    selected_flight = itinerary.get("selected_flight")
    selected_return_flight = itinerary.get("selected_return_flight")

    # Read the CSS file to inline it into the template
    css_path = _TEMPLATES_DIR / "itinerary.css"
    css_content = css_path.read_text(encoding="utf-8") if css_path.exists() else ""

    try:
        template = _jinja_env.get_template("itinerary.html")
        html_str = template.render(
            itinerary=itinerary,
            flight=flight,
            hotel=hotel,
            days=days,
            phrasebook=phrasebook,
            selected_flight=selected_flight,
            selected_return_flight=selected_return_flight,
            visa_data=req.visa_data,
            checklist_items=req.checklist_items,
            css=css_content,
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        )
    except Exception as exc:
        log.exception("Template rendering failed: %s", exc)
        raise HTTPException(status_code=500, detail=f"Template error: {exc}")

    try:
        pdf_bytes = weasyprint.HTML(string=html_str).write_pdf()
    except Exception as exc:
        log.exception("weasyprint PDF generation failed: %s", exc)
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {exc}")

    dest = itinerary.get("destination", "trip").replace(" ", "-").lower()
    filename = f"itinerary-{dest}.pdf"

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
