"""Airport lookup and search backed by the bundled OpenFlights dataset.

Data file: app/data/airports.json  (generated by scripts/fetch_airports.py)
Each entry: {iata, name, city, country, lat, lng}

Public API:
    lookup(query)        -> (iata, name, lat, lng) | None
    search(q, limit)     -> list[dict]
    lookup_alternates(city) -> list[(iata, name, lat, lng)]
"""
from __future__ import annotations

import json
import pathlib
import re

_DATA_PATH = pathlib.Path(__file__).parent.parent / "data" / "airports.json"

# Load once at import time.
_ALL: list[dict] = json.loads(_DATA_PATH.read_text(encoding="utf-8"))

# Two indexes for fast lookup.
_BY_IATA: dict[str, dict] = {a["iata"]: a for a in _ALL}
_BY_CITY: dict[str, dict] = {a["city"].lower(): a for a in _ALL}


# Tuple form used by existing callers: (iata, name, lat, lng)
def _to_tuple(a: dict) -> tuple[str, str, float, float]:
    return (a["iata"], a["name"], a["lat"], a["lng"])


def lookup(query: str) -> tuple[str, str, float, float] | None:
    """Resolve a city name, IATA code, or 'Name (IATA)' label to airport data.

    Priority order:
    1. Extract a 3-letter IATA code from the query (e.g. 'HKG' or 'Name (HKG)')
    2. Exact city name match (case-insensitive)
    3. Strip country suffix ('Tokyo, Japan' -> 'Tokyo') then retry step 2
    """
    if not query:
        return None
    q = query.strip()

    # 1. Try to find an IATA code: either a bare 3-letter code ("HKG") or
    #    the parenthesized format from the combobox ("Name (HKG)").
    q_up = q.upper()
    paren_match = re.search(r"\(([A-Z]{3})\)", q_up)
    if paren_match:
        entry = _BY_IATA.get(paren_match.group(1))
        if entry:
            return _to_tuple(entry)
    if re.fullmatch(r"[A-Z]{3}", q_up.strip()):
        entry = _BY_IATA.get(q_up.strip())
        if entry:
            return _to_tuple(entry)

    # 2. Exact city match (strip country suffix + "airport" suffix first).
    key = q.lower()
    if "," in key:
        key = key.split(",", 1)[0].strip()
    if key.endswith(" airport"):
        key = key[: -len(" airport")]
    entry = _BY_CITY.get(key)
    if entry:
        return _to_tuple(entry)

    return None


def search(q: str, limit: int = 10) -> list[dict]:
    """Return up to `limit` airports matching the query string.

    Searches IATA code, airport name, city, and country.
    Results are ranked: exact IATA > IATA prefix > city exact > city prefix
                        > name prefix > any substring.
    """
    q = q.strip().lower()
    if not q:
        return []

    scored: list[tuple[int, dict]] = []
    q_up = q.upper()

    for a in _ALL:
        iata = a["iata"]          # already uppercase
        name = a["name"].lower()
        city = a["city"].lower()
        country = a["country"].lower()

        if iata == q_up:
            score = 100
        elif iata.startswith(q_up):
            score = 80
        elif city == q:
            score = 70
        elif city.startswith(q):
            score = 60
        elif name.startswith(q):
            score = 50
        elif q in iata.lower() or q in city or q in name or q in country:
            score = 10
        else:
            continue

        scored.append((score, a))

    scored.sort(key=lambda x: -x[0])
    return [x[1] for x in scored[:limit]]


# ---------------------------------------------------------------------------
# Alternate airports per metro area — kept for flights.py alternate surfacing.
# ---------------------------------------------------------------------------
CITY_ALTERNATES: dict[str, list[tuple[str, str, float, float]]] = {
    "tokyo": [("HND", "Tokyo Haneda", 35.5494, 139.7798)],
    "osaka": [("ITM", "Osaka Itami (domestic)", 34.7854, 135.4383)],
    "seoul": [("GMP", "Seoul Gimpo", 37.5583, 126.7908)],
    "new york": [
        ("EWR", "Newark Liberty", 40.6925, -74.1687),
        ("LGA", "New York LaGuardia", 40.7769, -73.8740),
    ],
    "los angeles": [
        ("BUR", "Hollywood Burbank", 34.2007, -118.3587),
        ("LGB", "Long Beach", 33.8177, -118.1516),
    ],
    "san francisco": [
        ("OAK", "Oakland International", 37.7213, -122.2208),
        ("SJC", "San Jose International", 37.3626, -121.9290),
    ],
    "london": [
        ("LGW", "London Gatwick", 51.1537, -0.1821),
        ("STN", "London Stansted", 51.8860, 0.2389),
        ("LTN", "London Luton", 51.8747, -0.3683),
    ],
    "paris": [
        ("ORY", "Paris Orly", 48.7233, 2.3794),
        ("BVA", "Paris Beauvais", 49.4544, 2.1128),
    ],
    "milan": [
        ("LIN", "Milan Linate", 45.4451, 9.2767),
        ("BGY", "Bergamo Orio al Serio", 45.6739, 9.7042),
    ],
    "rome": [("CIA", "Rome Ciampino", 41.7994, 12.5949)],
    "moscow": [
        ("DME", "Moscow Domodedovo", 55.4088, 37.9063),
        ("VKO", "Moscow Vnukovo", 55.5914, 37.2615),
    ],
    "chicago": [("MDW", "Chicago Midway", 41.7868, -87.7522)],
    "washington": [
        ("DCA", "Reagan National", 38.8521, -77.0377),
        ("BWI", "Baltimore Washington", 39.1754, -76.6684),
    ],
    "houston": [("HOU", "Houston Hobby", 29.6454, -95.2788)],
    "toronto": [("YTZ", "Billy Bishop (downtown)", 43.6275, -79.3962)],
    "shanghai": [("SHA", "Shanghai Hongqiao", 31.1979, 121.3363)],
    "beijing": [("PKX", "Beijing Daxing", 39.5098, 116.4105)],
    "taipei": [("TSA", "Taipei Songshan (downtown)", 25.0697, 121.5519)],
    "istanbul": [("SAW", "Istanbul Sabiha Gokcen", 40.8986, 29.3092)],
    "dubai": [
        ("DWC", "Dubai Al Maktoum", 24.8966, 55.1614),
        ("AUH", "Abu Dhabi (alternate metro)", 24.4330, 54.6511),
    ],
    "bangkok": [("DMK", "Bangkok Don Mueang", 13.9130, 100.6066)],
}


def lookup_alternates(city: str) -> list[tuple[str, str, float, float]]:
    """Return alternate airports near a given city, or [] if none."""
    if not city:
        return []
    key = city.strip().lower()
    if "," in key:
        key = key.split(",", 1)[0].strip()
    if key.endswith(" airport"):
        key = key[: -len(" airport")]
    return CITY_ALTERNATES.get(key, [])
